# Generated by Django 2.1.7 on 2019-03-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('telefone_cliente', models.CharField(max_length=12)),
                ('pontos_cliente', models.IntegerField(max_length=10)),
                ('instagram_cliente', models.CharField(max_length=50)),
                ('bairro_cliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_produto', models.CharField(max_length=200)),
                ('pontos_produto', models.IntegerField(max_length=12)),
                ('valor_produto', models.FloatField(max_length=12)),
                ('marca_produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_servico', models.CharField(max_length=200)),
                ('pontos_servico', models.IntegerField(max_length=12)),
                ('valor_servico', models.FloatField(max_length=12)),
            ],
        ),
    ]
