# Generated by Django 2.1.7 on 2019-04-02 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0002_auto_20190401_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='hora_reserva',
            new_name='data_hora_reserva',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='data_reserva',
        ),
    ]
