# Generated by Django 2.2 on 2019-04-03 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0006_auto_20190402_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salao.Produto'),
        ),
    ]
