# Generated by Django 2.2 on 2019-04-03 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0007_auto_20190402_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='servico_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salao.Servico'),
        ),
    ]
