# Generated by Django 2.2 on 2019-04-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0008_auto_20190402_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='soma_pontos_venda',
            field=models.IntegerField(),
        ),
    ]
