# Generated by Django 2.2 on 2019-04-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0009_auto_20190402_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='soma_pontos_venda',
        ),
    ]
