# Generated by Django 2.1.7 on 2019-04-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0010_remove_venda_soma_pontos_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='teste',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
