# Generated by Django 2.1.7 on 2019-04-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0011_reserva_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='teste',
        ),
    ]
