# Generated by Django 2.1.7 on 2019-04-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0012_remove_reserva_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pontos_cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='produto_venda',
            field=models.ManyToManyField(to='salao.Produto'),
        ),
        migrations.RemoveField(
            model_name='venda',
            name='servico_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='servico_venda',
            field=models.ManyToManyField(to='salao.Servico'),
        ),
    ]
