# Generated by Django 2.1.7 on 2019-04-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0013_auto_20190403_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto_venda',
            field=models.ManyToManyField(related_name='produto_venda_set', to='salao.Produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='servico_venda',
            field=models.ManyToManyField(related_name='servico_venda_set', to='salao.Servico'),
        ),
    ]
