# Generated by Django 2.2 on 2019-04-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0014_auto_20190403_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='produto_venda',
            field=models.ManyToManyField(blank=True, to='salao.Produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='servico_venda',
            field=models.ManyToManyField(blank=True, to='salao.Servico'),
        ),
    ]
