# Generated by Django 2.1.7 on 2019-04-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0015_auto_20190404_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_hora_reserva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(default='2018-05-05'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_reserva',
            field=models.TimeField(default='08:08:00'),
        ),
    ]
