# Generated by Django 2.1.7 on 2019-04-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0016_auto_20190417_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hora_reserva',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_hora_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
