# Generated by Django 2.1.7 on 2019-05-06 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0017_auto_20190422_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(default=datetime.date(2019, 5, 6)),
        ),
    ]
