# Generated by Django 2.1.7 on 2019-05-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0018_auto_20190506_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(default='2019-05-05'),
        ),
    ]
