# Generated by Django 2.1.7 on 2019-05-08 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salao', '0020_auto_20190506_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateField(default=datetime.date(2019, 5, 8)),
        ),
    ]
